homeassistant: true
permit_join: true
advanced:
  log_level: debug
  network_key: '!secret network_key'
  channel: 20
  last_seen: epoch
  report: true
  availability_timeout: 15
  availability_whitelist:
    - '0x680ae2fffe3f7d56'
  adapter_concurrent: 6
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.40'
  user: '!secret mqtt_user'
  password: '!secret mqtt_pass'
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L430018T-if00
groups:
  '1':
    friendly_name: stuegruppe
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0x00124b001efe6145'
      - '0x000d6ffffeba7b5e'
      - '0xd0cf5efffe6f53b3'
      - '0xd0cf5efffe05c545'
      - '0x90fd9ffffe901c13'
      - '0x90fd9ffffe877eef'
      - '0x14b457fffe4422c9'
      - '0x000b57fffe998cf0'
      - '0x000b57fffe48bce7'
      - '0x000b57fffe8d2387'
      - '0x000b57fffeb1e89b'
      - '0x0017880102c4eb36'
      - '0x086bd7fffe4141ed'
      - '0x000d6ffffefcde8b'
      - '0xd0cf5efffe05cb38'
      - '0x588e81fffe1001f0'
      - '0x588e81fffe0e784d'
  '2':
    friendly_name: kjokkengruppe
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0x000b57fffedce5c1'
      - '0x000b57fffe9eaa7b'
      - '0x0017880102c4e0ca'
      - '0x00124b001d3aa934'
      - '0x0017880108166f57'
      - '0x680ae2fffe3f7d56'
  '3':
    friendly_name: kjellergruppe
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0x90fd9ffffe336d40'
      - '0x90fd9ffffe4c6bec'
      - '0x000b57fffeb8ee22'
      - '0x90fd9ffffe792ee9'
      - '0x000b57fffed45fde'
      - '0x000b57fffed5269f'
  '4':
    friendly_name: eirikgruppe
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0x000b57fffed9807d'
      - '0x90fd9ffffe71813d'
      - '0x90fd9ffffe723f2a'
  '5':
    friendly_name: soveromgruppe
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0x0017880104259fb3'
      - '0x0017880104259fa6'
  '6':
    friendly_name: utegruppe
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0xec1bbdfffeeb3deb'
      - '0xd0cf5efffee9ee80'
      - '0xec1bbdfffeeb440e'
      - '0x086bd7fffe254322'
      - '0xd0cf5efffe44e080'
      - '0xd0cf5efffe1572af'
devices:
  '0x00124b001efe6145':
    friendly_name: Stue Peislys
  '0x000d6ffffeba7b5e':
    friendly_name: Stue Lite vitrineskap
  '0xd0cf5efffe6f53b3':
    friendly_name: Stue lyst vitrineskap
  '0xd0cf5efffe05c545':
    friendly_name: Stue Bikkjelampe
  '0x90fd9ffffe901c13':
    friendly_name: Stue Vinduslampe1
  '0x90fd9ffffe877eef':
    friendly_name: Stue Vinduslampe2
  '0x14b457fffe4422c9':
    friendly_name: Stue Stuebord
  '0x000b57fffe998cf0':
    friendly_name: Stue Gulvlampe1
  '0x000b57fffe48bce7':
    friendly_name: Stue Gulvlampe3
  '0x000b57fffe8d2387':
    friendly_name: Stue Gulvlampe2
  '0x000b57fffeb1e89b':
    friendly_name: Stue Stort Vitrineskap
  '0x0017880102c4eb36':
    friendly_name: Stue Lys Bak TV
  '0x00158d00027d72a0':
    friendly_name: Alva Kube
  '0x00158d0002b85baf':
    friendly_name: Kontor Bevegelse Eirik
  '0xd0cf5efffe2b0d81':
    friendly_name: Do Vegglampe
  '0xd0cf5efffef71dcb':
    friendly_name: Do Hyllelampe
  '0x000b57fffedce5c1':
    friendly_name: Kjokken Vinduslampe
  '0x000b57fffe9eaa7b':
    friendly_name: Kjokken Benkelys
  '0x0017880102c4e0ca':
    friendly_name: Kjokken Taklampe
  '0x00124b001d3aa934':
    friendly_name: Kjokken Benke Underlys
  '0x0017880108166f57':
    friendly_name: Kjokken Bordlampe
  '0xd0cf5efffe05cb38':
    friendly_name: Stue Ganglys
  '0xec1bbdfffeeb3deb':
    friendly_name: Ute Ovre Lys Garasje
  '0xd0cf5efffee9ee80':
    friendly_name: Ute Bak Hoyre Oppe
  '0xec1bbdfffeeb440e':
    friendly_name: Ute Ovre Lys Trapp
  '0x086bd7fffe254322':
    friendly_name: Ute Nedre Lys Garasje
  '0x086bd7fffe53cdb2':
    friendly_name: '0x086bd7fffe53cdb2'
  '0xd0cf5efffe44e080':
    friendly_name: Ute Bak Hoyre Nede
  '0x680ae2fffe109777':
    friendly_name: '0x680ae2fffe109777'
  '0x90fd9ffffed967af':
    friendly_name: '0x90fd9ffffed967af'
  '0xd0cf5efffe1572af':
    friendly_name: Ute Ovre Lys Ytterdor
  '0xec1bbdfffeebf732':
    friendly_name: '0xec1bbdfffeebf732'
  '0x0017880104f089cd':
    friendly_name: Kjokken Fjernkontroll
  '0x086bd7fffe4141ed':
    friendly_name: Stue Stalampe
  '0x000d6ffffefcde8b':
    friendly_name: Stue Gangbordlampe
  '0x000d6ffffee3f3d5':
    friendly_name: Stue Veggbryteren
  '0x00158d00028a19cf':
    friendly_name: Do Dodor
  '0x00158d00028b6bbb':
    friendly_name: Kjeller Kjellerdor
  '0x90fd9ffffe336d40':
    friendly_name: Kjeller Trappelys
  '0x90fd9ffffe4c6bec':
    friendly_name: Kjeller Ganglys
  '0x00158d0002890282':
    friendly_name: Kjeller Boddor
  '0x000b57fffec4f858':
    friendly_name: Kjeller Bod
  '0x000b57fffeb8ee22':
    friendly_name: Kjeller Fryserom
  '0x00158d0002b6e52f':
    friendly_name: Kjeller Vaskerom Bevegelse
  '0x90fd9ffffe792ee9':
    friendly_name: Kjeller Vaskerom3
  '0x000b57fffed45fde':
    friendly_name: Kjeller Vaskerom2
  '0x000b57fffed5269f':
    friendly_name: Kjeller Vaskerom1
  '0x00158d00028a1a0e':
    friendly_name: Kjeller Garasjedor
  '0x000b57fffed9807d':
    friendly_name: Eirik Kontor1
  '0x90fd9ffffe71813d':
    friendly_name: Eirik Kontor2
  '0x90fd9ffffe723f2a':
    friendly_name: Eirik Kontor3
  '0x00158d0002e91e9a':
    friendly_name: Bad Temperatur
  '0x00158d0002720f9f':
    friendly_name: Alva Temperatur
  '0x00158d0002130a5b':
    friendly_name: Kjokken Lyskontroll
  '0x00158d0001e83e74':
    friendly_name: Loft Veggbryter
  '0x00158d000272cf43':
    friendly_name: Loft Temperatur
  '0x00158d00042457ef':
    friendly_name: Soverom Bryter W
  '0x00158d000428fa3b':
    friendly_name: Soverom Bryter Eirik
  '0x00158d00025efd10':
    friendly_name: Soverom Temperatur
  '0x00158d00025f040e':
    friendly_name: Bod Temperatur
  '0x00158d0002733f1a':
    friendly_name: Vaskerom Temperatur
  '0x90fd9ffffeea8593':
    friendly_name: Alva Taklampe
  '0x000b57fffe8a0ad9':
    friendly_name: Alva Skylampe
  '0x00158d0002e94b50':
    friendly_name: Garasje Temperatur
  '0x0017880104259fb3':
    friendly_name: Soverom Lampe W
  '0x0017880104259fa6':
    friendly_name: Soverom Lampe Eirik
  '0x00158d0001e83dba':
    friendly_name: Ringeklokke
  '0x00178801067347bc':
    friendly_name: '0x00178801067347bc'
  '0x680ae2fffe3f7d56':
    friendly_name: Kjokken Ventilator
  '0x588e81fffe1001f0':
    friendly_name: Stue Yttergang Tak
  '0x588e81fffe0e784d':
    friendly_name: Stue mellomgang
  '0x00158d0002130e2c':
    friendly_name: '0x00158d0002130e2c'
  '0x00158d0002b8fdf9':
    friendly_name: '0x00158d0002b8fdf9'
  '0x000b57fffe89df9e':
    friendly_name: Loft Gulvlampe3
  '0x000b57fffe48b86e':
    friendly_name: Loft Gulvlampe2
  '0x000b57fffe8b1882':
    friendly_name: Loft Gulvlampe1
  '0xd0cf5efffe1f5be3':
    friendly_name: '0xd0cf5efffe1f5be3'
  '0x00124b000be5ac60':
    friendly_name: '0x00124b000be5ac60'
  '0x00158d0002720f9b':
    friendly_name: '0x00158d0002720f9b'
  '0x00124b001ca60b3c':
    friendly_name: '0x00124b001ca60b3c'
